### PR TITLE
suggested changes to layout and content and addition of gitignore

### PR DESCRIPTION
**Pull request by davjfish**
- addition of gitignore file

### CODE REVIEW

**Comment by claudenozeres** [comment]
species summary needs to have an additional name - original 'scientific name' depends on regional checklist. This is sometimes, but not always, an **actual** scientific name. So, the full order could be:
code, _verbatimIdentification_ (A string representing the taxonomic identification as it appeared in the original record, https://dwc.tdwg.org/terms/), common name EN, common name FR (if presented), scientificName (= exists in WoRMS), taxonID (WoRMS AphiaID). In order to find the gaps and exceptions, I worked with merging (concatenating) several fields to inform as a key to each code in each region (see merged file sent by email).

**Comment by claudenozeres** [comment]
To have a starting point for discussion, each region will be asked to provide the following:
(should be examined before the workshop?)
for their "flagship" survey (e.g. July for Maritimes, August for Quebec, September for Gulf), a table showing the number of times per year that each species code has been used in the catch table.
(this will make a long table--how many years going back, should indicate? Or we will see).
for those species codes identified in 1), detailed entries from regional species list
(what are detailed entries?)
for those species codes identified in 1), do they have an AphiaID?
All taxonomic items will have an AphiaID, yes. I sent a file.

**Comment by davjfish** [comment]
Hi Claude, thanks for the comments and for the merged code list. 

In the context of this meeting, I think the value behind this exercise is much less ambitious than what you have tackled in your work. It seems to me that our regional lists are much larger than the subset of species that we actually record on a year-to-year basis. This is at least the case in our region where our species table in Oracle has thousands of records whereas the actual number of observed species is probably an order of magnitude less. 

My interest in the scope of Andes is simply to look at a list of species from each region, ranked by order of observation frequency. I want to avoid the use of Andes as the resting place for our national species list. But perhaps that would be a cool project for DM Apps? In any case, we can hash this out in person next month. 

Thoughts? 

p.s., I'll attach the file you emailed me to this thread.

[codes_DFO_CaRMS_2022-02-02 (3).xlsx](https://github.com/ricardd/Atlantic-Surveys-Species-Lists-Workshop-2022/files/10031623/codes_DFO_CaRMS_2022-02-02.3.xlsx)

**Comment by claudenozeres** [comment]
Hi David, I agree! I mention the file because it is a starting point to see the many codes in use across regions, and the sources of potential conflicts for a an Atlantic set, and then regional subsets that share the same names/codes, but should also be display far fewer in number for some regions (e.g., nGSL, sGSL) compared to the open Atlantic. In Quebec (nGSL) have 8K+ marine names, 2K+ on surveys, yet only 500 actual taxa in records across 20 years.

**Pull request merged**
